[project]
name = "sophia"
version = "0.0"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)

[build-system]
requires = [
    "setuptools",
]
